[mhed31] Implement Vulkan renderer
Sckorn/rcbe_engine pull request #70
Opened 2023-10-12 06:27 UTC by Sckorn

Iplement VulkanAPI based graphics renderer. Due to limited environment for development, first version is limited and has certain issues, which will be fixed after porting to windows.

2023-10-25 07:19 UTC, radameon requested changes
You need to fix all these suggestions. And we're good to go.

2023-10-25 07:19 UTC, radameon commented on renderer/src/VulkanRenderer.cpp
> +						   std::addressof(mpc));
Indentation.

2023-10-25 07:19 UTC, radameon commented on renderer/src/VulkanRenderer.cpp
> +						 prev_verts_count, 0);
Indentation.

2023-10-25 07:19 UTC, radameon commented on renderer/src/VulkanRenderer.cpp
> +	}
Can be made into separate function.

2023-10-25 07:19 UTC, radameon commented on renderer/src/VulkanRenderer.cpp
> +}*/
Remove commented code.

2023-10-26 18:05 UTC, Sckorn commented on .github/workflows/main.yml
>      - name: Set up GCC
Done vulkan jobs, opengl jobs would be done when all other suggestions are fixed.

2023-10-26 18:06 UTC, Sckorn commented on camera/src/Camera.cpp
> +    direction_ = -res.getRow(2).decreasedDimension().normalized();
Maybe `lowerDimension`?

2023-10-27 18:36 UTC, Sckorn commented on WORKSPACE
> +    name = "stbi",
It's MIT license and can be used in commercial closed-source project. We can leave it for reference.

2023-10-28 17:41 UTC, Sckorn commented on camera/src/Camera.cpp
> +    return std::move(pitch);
Clangd sais the opposite, without move it will be copied despite deng returned by name.

2023-10-28 17:44 UTC, Sckorn commented on camera/src/Camera.cpp
> +    pitch_ = clampPitch(std::move(pitch_));
It can't be copied since method expects reference of any kind.

2023-10-28 17:45 UTC, Sckorn commented on camera/src/Camera.cpp
> +    pitch_ = clampPitch(std::move(pitch_));
Double checking

2023-10-28 18:10 UTC, Sckorn commented on camera/src/Camera.cpp
> +    pitch_ = clampPitch(std::move(pitch_));
Oh and pitch is changed in the line above 😄

2023-10-28 18:11 UTC, Sckorn commented on camera/src/Camera.cpp
> +    pitch_ = clampPitch(std::move(pitch_));
Yeah, it is changed in the line right above.

2023-10-28 18:37 UTC, Sckorn commented on datamodel/BUILD
> +        "//meta_package:rdmn_vk_rasterizer_backend": [],
Apparently no, since and builds and runs successfully

2023-10-28 18:48 UTC, Sckorn commented on datamodel/include/datamodel/math/Matrix.hpp
> +            _tmp[i] = m_[i + ROWS * index];
No, the computation is right.

2023-10-28 18:49 UTC, Sckorn commented on datamodel/include/datamodel/rendering/Material.hpp
> +#include <rcbe-engine/datamodel/rendering/RasterizerTexture.hpp>
These two abstragate the actual implementation.

2023-10-29 10:29 UTC, Sckorn commented on datamodel/include/datamodel/rendering/Shader.hpp
> +bool operator==(const rdmn::render::Shader &lhs, const rdmn::render::Shader &rhs);
Path and type, if it bugs you I can remove it.

2023-10-30 17:23 UTC, Sckorn commented on datamodel/BUILD
> +        "RDMN_GLM_INTEGRATION",
`RCBE_SCALAR_LINALG` is needed, the second one I removed.

2023-10-30 17:45 UTC, Sckorn commented on datamodel/data/rendering/vulkan_camera_config.json
> +  "maximum_fov": 60.0,
I think it can be done later.

2023-10-30 18:10 UTC, Sckorn commented on datamodel/include/datamodel/core/Dimensions.hpp
> +using FloatDimensions = dimensions_impl<float>;
I'll add a to do, to handle this case.

2023-10-30 18:34 UTC, Sckorn commented on datamodel/include/datamodel/math/Matrix.hpp
>  rcbe::math::Matrix3x3 operator+(const rcbe::math::Matrix3x3 &lhs, const rcbe::math::Matrix3x3 &rhs);
I'll leave a TODO: need to merge this ASAP.

2023-10-30 18:37 UTC, Sckorn commented on datamodel/include/datamodel/math/Vector.hpp
> +using Vector2i = Vector<int32_t, 2>;
Seems to verbose, want to keep it simpler.

2023-11-01 17:13 UTC, Sckorn commented on datamodel/include/datamodel/math/Vector.hpp
> +    /// TODO: deprecate this, intoriduce conversion operator (explicit!!!) @sckorn
Introduced conversion op, left the method, to useit inside op.

2023-11-01 17:31 UTC, Sckorn commented on datamodel/include/datamodel/rendering/Material.hpp
> -    mutable std::vector<visual::Texture> textures_;
Will check when will build OpenGL version.

2023-11-01 17:33 UTC, Sckorn commented on datamodel/include/datamodel/rendering/Material.hpp
> +    bool deferred_ = false;
Yeah, it is used, although some logic around it, changed, OpenGL back would most likely have dificulties, I'll check it.

2023-11-01 17:57 UTC, Sckorn commented on datamodel/include/datamodel/rendering/RasterizerTexture.hpp
> +    [[nodiscard]] bool init(VkDevice logical_device,
I'll leave a TODO to refactor this, since right now it might take too much time.

2023-11-01 18:23 UTC, Sckorn commented on datamodel/include/datamodel/rendering/VulkanGraphicsPipeline.hpp
> +private:
Fail to see any reason to do it.

2023-11-03 16:21 UTC, Sckorn commented on datamodel/include/datamodel/rendering/Shader.hpp
> +bool operator==(const rdmn::render::Shader &lhs, const rdmn::render::Shader &rhs);
Removed.

2023-11-03 16:42 UTC, Sckorn commented on datamodel/include/datamodel/rendering/buffer_object_helpers.hpp
> +                        /// TODO: fix this to make it work properly @sckorn @radameon
Ok, I'll remove it, since I don't remember what this is about.

2023-11-03 16:48 UTC, Sckorn commented on datamodel/include/datamodel/rendering/renderer_config.hpp
> +    bool debug = true;
Yeah, it enables or disables validation layers.

2023-11-03 17:09 UTC, Sckorn commented on datamodel/include/datamodel/visual/Texture.hpp
> +  	VisualTextureSet(std::unordered_set<TexturePtr> &&tex_data);
Non const ones are stored, I can introduce another class for constant ones.

2023-11-03 18:01 UTC, Sckorn commented on datamodel/src/rendering/Material.cpp
> +		BOOST_LOG_TRIVIAL(warning) << "Too many shaders supplied, material expects one vertex and one fragment shader!";
I'd say this is for the future changes.

2023-11-03 18:05 UTC, Sckorn commented on datamodel/src/rendering/Shader.cpp
> +#ifdef RDMN_VULKAN
I'll leave a TODO

2023-11-03 18:06 UTC, Sckorn commented on datamodel/src/rendering/Shader.cpp
> +#ifdef RDMN_VULKAN
Wait there is no pImpl, there's an object.

2023-11-03 18:10 UTC, Sckorn commented on datamodel/src/rendering/renderer_config.cpp
> +            {"renderer_type", rcbe::rendering::str_from_renderer_type(conf.renderer_type)}
Minor cahnge. Will return it.

2023-11-03 18:10 UTC, Sckorn commented on datamodel/src/visual/RGBAColor.cpp
> +        static_cast<ValueType>(extract_color_byte(hex_code, 3)) / COLOR_COMPONENT_DIVIDER,
Yeah, it was.

2023-11-03 18:20 UTC, Sckorn commented on parsers/BUILD
> +cc_binary(
I think it can be used, when testing more different files.

2023-11-04 10:30 UTC, Sckorn commented on datamodel/src/rendering/VulkanGraphicsPipeline.cpp
> +  viewport.maxDepth = 1.f;
I do believe that these are normalized values, so no need to use near and far here.

2023-11-04 10:48 UTC, Sckorn commented on thirdparty/stbi.BUILD
> +)
I think we might need it.

2023-11-04 10:48 UTC, Sckorn commented on parsers/src/gltf/main.cpp
> +    return 0;
Agree

2023-11-04 18:04 UTC, Sckorn commented on datamodel/src/rendering/rasterizer_texture_helpers.cpp
> +bool generateMipmaps(
Can't find it.

2023-11-04 18:05 UTC, Sckorn commented on renderer/BUILD
> +    ],  # TODO: remove after debugging
Nope, some of the resources are preloaded, and would be as well (skybox). I'll remove a TODO.

2023-11-04 18:10 UTC, Sckorn commented on renderer/BUILD
> +        "RDMN_DEBUG_MODE",
Removed them.

2023-11-04 18:24 UTC, Sckorn commented on parsers/src/tga/tga_parser.cpp
> +            color_comp_bytes.resize(pixel_depth_bytes, 0);
Nope, I reserve uninit memory, and then resize the vector to elements size.

2023-11-04 18:30 UTC, Sckorn commented on renderer/src/VulkanRenderer.hpp
> +    struct image_view_creation_result {
Yup

2023-11-04 18:31 UTC, Sckorn commented on renderer/src/GLRenderer.cpp
> +                bool hardware_renderer = (config_.renderer_type == rcbe::rendering::RendererType ::hardware);
Since GL renderer is low priority, I'll leave a TODO.

2023-11-04 18:36 UTC, Sckorn commented on parsers/src/gltf/gltf_parser.cpp
> +                rcbe::visual::RGBAColor(0x88AABBFF)
I'll make it gray

2023-11-04 18:47 UTC, Sckorn commented on renderer/src/VulkanRenderer.cpp
> +	}
I'll try but right now the logic in two blocks of code that use it, is a lil' but different, so no guarantee.

2023-11-05 17:13 UTC, Sckorn commented on datamodel/src/rendering/rasterizer_texture_helpers.cpp
> +bool generateMipmaps(
Found it, and fixed.

2023-11-05 17:17 UTC, Sckorn commented on renderer/src/VulkanRenderer.cpp
> +    app_info.pApplicationName = "RDMN Renderer";
I'll do it via constant, but it seems it should be in config.

2023-11-07 17:08 UTC, Sckorn commented
OpenGL renderer builds and even shows something, though only one of the three meshes are shown properly, and there is some problem with rotations, but we can leave this be for now.

2023-11-08 18:24 UTC, radameon requested changes
This will require a lot of refactoring in the future, but since we've been on this for more then a year, you need to fix these last things, and we're good to go.

2023-11-08 18:24 UTC, radameon commented on input_manager/include/core/EditorInputManager.hpp
> -                        if (static_cast<double>(pitch.as_deg()) <= 90.) {
This removed code, might also hinder the work of OpenGL renderer, so you should use `ifdef`s here.

2023-11-08 18:24 UTC, radameon commented on renderer/src/VulkanRenderer.cpp
> +      //added_object_.store(false);
remove comment.

2023-11-08 18:24 UTC, radameon commented on renderer/src/VulkanRenderer.cpp
> +rcbe::core::CoreObject loadCorner() {
Move this whole anonymous namespace to the up of the file.

2023-11-08 18:24 UTC, radameon commented on renderer/src/VulkanRenderer.cpp
> +            ); // TODO: fix mip calculation here
TODO can be removed now.

2023-11-08 18:24 UTC, radameon commented on renderer/src/VulkanRenderer.cpp
> +                               config_.initial_dimensions.height)); // TODO: fix mip calculation here
You still haven't fixed it here.

2023-12-22 16:45 UTC, Sckorn commented on camera/include/camera/Camera.hpp
> -    math::yaw yaw_ { math::deg(-90.)};
Did this, it didn't help. Will have to debug this later.

2024-01-12 18:54 UTC, Sckorn commented on datamodel/include/datamodel/rendering/RenderingContext.hpp
>      rcbe::math::deg zoom_ = rcbe::math::deg(45.);
Made it so this is updated witrh default ofv from camera in Camera's ctor. will remove default value here.

2024-01-12 19:01 UTC, Sckorn commented on datamodel/src/rendering/Shader.cpp
> +    [[nodiscard]] VkShaderModule handle() const noexcept;
`const` is redundant here.

2024-01-13 17:07 UTC, radameon requested changes
Just a lil' bit left, and we're good to  go.

2024-01-13 17:26 UTC, Sckorn commented
I left a `TODO` for comment https://github.com/Sckorn/rcbe_engine/pull/70#discussion_r1451566948, since making it default (i.e. zero), breaks the scene view.

2024-01-13 17:30 UTC, radameon commented
Okay, also I see that one test fail for OpenGL pipeline, please file a bug leave a TODO in code, and disable test for OpenGL. And we're pretty much done and ready to merge.

2024-01-13 17:44 UTC, radameon approved these changes
Squash and merge this bad boy.

2024-01-13 17:44 UTC, radameon commented on datamodel/include/datamodel/rendering/RenderingContext.hpp
>      rcbe::math::deg zoom_ = rcbe::math::deg(45.);
Ok, I can see a TODO this is fine for now.

2024-01-13 18:25 UTC, merged

2024-01-13 18:25 UTC, radameon commented
:partying_face: :fireworks: :tada: