[WT12] Trivial logger
Sckorn/rcbe_engine pull request #79
Opened 2024-10-25 17:56 UTC by Sckorn

2024-10-25 18:19 UTC, radameon requested changes
Needs some more work

2024-10-25 18:19 UTC, radameon commented on common/include/common/logger/trivial_logger.hpp
> +#include <iostream>
Still needed?

2024-10-25 18:19 UTC, radameon commented on common/include/common/logger/trivial_logger.hpp
> + * in order to reduce th needed changes when doing refactoring of many,
`...the need...`

2024-10-25 18:19 UTC, radameon commented on common/include/common/logger/trivial_logger.hpp
> + * This implementation will be replacedby a proper logger, which will be supplied to classes which require it,
`...replaced by...`

2024-10-25 18:19 UTC, radameon commented on common/include/common/logger/trivial_logger.hpp
> +            iss_ << '\0';
This function looks pretty strange, why in the loop above it's `i < Size - 1` and then you have zero terminator check and addtition?

2024-10-25 18:19 UTC, radameon commented on common/src/logger/trivial_logger.cpp
> +    LOG(INFO) << str; // no trace in GLOG
`no debug in GLOG`

2024-10-25 18:19 UTC, radameon commented on common/src/logger/trivial_logger.cpp
> +    LOG(WARNING) << str; // no trace in GLOG
Comment is wron, there is a warn log level in GLOG.

2024-10-25 18:19 UTC, radameon commented on common/src/logger/trivial_logger.cpp
> +    LOG(ERROR) << str; // no trace in GLOG
`// fatal in GLOG terminates the program, so shouldn't be used`

2024-10-25 18:19 UTC, radameon commented on common/src/logger/trivial_logger.cpp
> +                log_fatal(iss_.str());
Mark all of the above `noexcept`

2024-10-25 18:19 UTC, radameon commented on thirdparty/glog.BUILD
> +glog_library(0)
Add a comment why.

2024-10-25 19:25 UTC, Sckorn commented on common/src/logger/trivial_logger.cpp
> +                log_fatal(iss_.str());
Done

2024-10-26 14:01 UTC, radameon requested changes
One more test case is needed.

2024-10-26 14:14 UTC, radameon approved these changes
Squash and merge, if CI is good.

2024-10-26 14:43 UTC, merged